import { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { api } from './services/api';
import DataTable from './components/DataTable';
import ResourcePage from './components/ResourcePage';

export function TransactionsPage() {
    const [rows, setRows] = useState([]); const [types, setTypes] = useState([]); const [categories, setCategories] = useState([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState({ type: '', category: '', date: '', amount: '', description: '' });
    const load = () => api.transactions.list().then(setRows); useEffect(() => { load(); api.types.list().then(setTypes); }, []); useEffect(() => { if (form.type) api.categories.list(form.type).then(setCategories); }, [form.type]);
    const save = async (event) => { event.preventDefault(); const data = { ...form, title: form.description.trim(), amount: Number(form.amount), date: new Date(form.date).toISOString() }; if (!data.title) return; if (editing) await api.transactions.update(editing._id, data); else await api.transactions.create(data); setOpen(false); setEditing(null); setForm({ type: '', category: '', date: '', amount: '', description: '' }); load(); };
    const remove = async (row) => { if (window.confirm('Delete this transaction?')) { await api.transactions.remove(row._id); load(); } };
    const columns = [{ key: 'type', label: 'Type' }, { key: 'category', label: 'Category' }, { key: 'date', label: 'Date & time', render: (row) => new Date(row.date).toLocaleString() }, { key: 'amount', label: 'Amount', render: (row) => `₹${Number(row.amount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}` }, { key: 'description', label: 'Description' }];
    return <div className="resource-page"><div className="resource-heading"><div><p className="eyebrow">Ledger</p><h1>Transactions</h1><p className="subheading">Every income and expense, in descending order.</p></div><button className="primary-button" onClick={() => setOpen(true)}><Plus size={18} />Add transaction</button></div><section className="panel resource-panel"><DataTable columns={columns} rows={rows} onEdit={(row) => { setEditing(row); setForm({ ...row, date: new Date(row.date).toISOString().slice(0, 16) }); setOpen(true); }} onDelete={remove} /></section>{open && <div className="modal-backdrop"><div className="modal"><div className="modal-heading"><div><p className="eyebrow">Ledger entry</p><h2>{editing ? 'Edit transaction' : 'Add transaction'}</h2></div><button className="icon-button" onClick={() => setOpen(false)}>×</button></div><form onSubmit={save}><label>Type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value, category: '' })} required><option value="">Select type</option>{(types.length ? types.map((item) => item.name) : ['Income', 'Expense', 'Others']).map((item) => <option key={item}>{item}</option>)}</select></label><label>Category<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} required><option value="">Select category</option>{categories.map((item) => <option key={item._id}>{item.name}</option>)}</select></label><label>Date and time<input type="datetime-local" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} required /></label><label>Amount<input type="number" min="0" step="0.01" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} required /></label><label>Description<input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><button className="primary-button modal-submit">Save transaction</button></form></div></div>}</div>;
}

export function MastersPage() { const [tab, setTab] = useState('types'); const [rows, setRows] = useState([]); const [types, setTypes] = useState([]); const [name, setName] = useState(''); const [type, setType] = useState(''); const [editing, setEditing] = useState(null); const load = () => (tab === 'types' ? api.types.list() : api.categories.list()).then(setRows); useEffect(() => { api.types.list().then(setTypes); }, []); useEffect(() => { load(); }, [tab]); const add = async (event) => { event.preventDefault(); const data = { name, ...(tab === 'categories' ? { type } : {}) }; if (editing) await (tab === 'types' ? api.types.update(editing._id, data) : api.categories.update(editing._id, data)); else await (tab === 'types' ? api.types.create(data) : api.categories.create(data)); setName(''); setType(''); setEditing(null); load(); }; const remove = async (row) => { if (window.confirm('Delete this master record?')) { await (tab === 'types' ? api.types.remove(row._id) : api.categories.remove(row._id)); load(); } }; return <div className="resource-page"><div className="resource-heading"><div><p className="eyebrow">Configuration</p><h1>Masters</h1><p className="subheading">Define transaction types and type-specific categories.</p></div></div><div className="master-tabs"><button className={tab === 'types' ? 'selected' : ''} onClick={() => { setTab('types'); setEditing(null); }}>Types</button><button className={tab === 'categories' ? 'selected' : ''} onClick={() => { setTab('categories'); setEditing(null); }}>Categories</button></div><section className="panel resource-panel"><form className="inline-form" onSubmit={add}><input placeholder={tab === 'types' ? 'New type name' : 'New category name'} value={name} onChange={(event) => setName(event.target.value)} required />{tab === 'categories' && <select value={type} onChange={(event) => setType(event.target.value)} required><option value="">Select type</option>{types.map((item) => <option key={item._id}>{item.name}</option>)}</select>}<button className="primary-button"><Plus size={16} />{editing ? 'Update' : 'Add'}</button></form><DataTable columns={tab === 'types' ? [{ key: 'name', label: 'Type name' }] : [{ key: 'name', label: 'Category name' }, { key: 'type', label: 'Transaction type' }]} rows={rows} onEdit={(row) => { setEditing(row); setName(row.name); setType(row.type || ''); }} onDelete={remove} /></section></div>; }

export const UsersPage = () => <ResourcePage title="Users" description="Manage customer accounts and subscription access." resource={api.users} columns={[{ key: 'name', label: 'Name' }, { key: 'phoneNumber', label: 'Phone number' }, { key: 'emailId', label: 'Email' }, { key: 'userName', label: 'Username' }, { key: 'subscriptionPlan', label: 'Plan' }, { key: 'approvalStatus', label: 'Status' }, { key: 'subscriptionStartDate', label: 'Start date', render: (row) => row.subscriptionStartDate ? new Date(row.subscriptionStartDate).toLocaleDateString() : '-' }, { key: 'subscriptionEndDate', label: 'End date', render: (row) => row.subscriptionEndDate ? new Date(row.subscriptionEndDate).toLocaleDateString() : '-' }]} fields={[{ key: 'name', label: 'Name' }, { key: 'phoneNumber', label: 'Phone number' }, { key: 'emailId', label: 'Email', type: 'email' }, { key: 'userName', label: 'Username' }, { key: 'password', label: 'Password', type: 'password', required: false }, { key: 'subscriptionPlan', label: 'Subscription plan', required: false }, { key: 'approvalStatus', label: 'Approval status', options: ['pending', 'approved', 'rejected'], required: false }, { key: 'subscriptionStartDate', label: 'Subscription start date', type: 'date', required: false }, { key: 'subscriptionEndDate', label: 'Subscription end date', type: 'date', required: false }]} />;
export const SubscriptionsPage = () => <ResourcePage title="Subscriptions" description="Manage plans and billing periods." resource={api.subscriptions} columns={[{ key: 'planName', label: 'Plan name' }, { key: 'period', label: 'Period' }, { key: 'amount', label: 'Amount', render: (row) => `₹${Number(row.amount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}` }]} fields={[{ key: 'planName', label: 'Plan name' }, { key: 'period', label: 'Period', options: ['1 month', '3 months', '6 months', '1 year'] }, { key: 'amount', label: 'Amount', type: 'number' }]} />;
